2 mantenimiento de desastres fenomenos y monedas
Desarrollo-cit/medios-comunicacion pull request #10
Opened 2023-01-18 23:07 UTC by calo13

2023-01-18 23:10 UTC, Dfj9705 requested changes
Terminar los demas mantenimientos
X-Requested-With

2023-01-20 15:12 UTC, Dfj9705 requested changes
Alertas en mayusculas

2023-01-20 16:49 UTC, Dfj9705 requested changes
Ocurrió con tilde

2023-01-23 14:41 UTC, Dfj9705 approved these changes

2023-01-23 14:42 UTC, merged

2023-01-23 14:42 UTC, calo13 commented
tarea finalizada